SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE IF NOT EXISTS `usuarios` 
( `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,  
	`nombre` VARCHAR(50) NOT NULL ,  
	`clave` VARCHAR(60) NOT NULL ,  
	`perfil` VARCHAR(50) NOT NULL ,    
	`sexo` VARCHAR(50) NOT NULL ,    
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY  (`id`),    
	UNIQUE  `ukNombre` (`nombre`)) 
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `compras` 
( `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,  
	`id_usuario` BIGINT(20) UNSIGNED NOT NULL ,  
	`articulo` VARCHAR(50) NOT NULL ,  
	`fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`precio` FLOAT NOT NULL ,    
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY  (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `logs` 
( `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,  
	`id_usuario` BIGINT(20) UNSIGNED NOT NULL ,  
	`metodo` VARCHAR(50) NOT NULL ,  
	`ruta` VARCHAR(250) NOT NULL ,  
	`fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY  (`id`))
ENGINE = InnoDB;
